import json
import subprocess
import tempfile
import unittest
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import Optional


REPO = Path(__file__).resolve().parents[1]
CLI = REPO / "nda_review_cli.py"


def quickstart(td: Path, answers: Optional[dict] = None) -> None:
    cmd = ["python3", str(CLI), "quickstart", "--base", str(td), "--no-prompt", "--yes"]
    if answers is not None:
        ans_path = td / "_answers.json"
        ans_path.parent.mkdir(parents=True, exist_ok=True)
        ans_path.write_text(json.dumps(answers))
        cmd += ["--answers-file", str(ans_path)]
    subprocess.check_call(cmd, cwd=REPO)


class DraftTests(unittest.TestCase):
    def test_mutual_draft_substitutes_parties_and_policy_clause_text(self):
        td = Path(tempfile.mkdtemp(prefix="nda-draft-mutual-"))
        quickstart(td)
        out_md = td / "output" / "drafts" / "mutual.md"
        out_docx = td / "output" / "drafts" / "mutual.docx"
        subprocess.check_call(
            [
                "python3", str(CLI), "draft",
                "--base", str(td),
                "--template", "mutual",
                "--party-a", "Acme Inc.",
                "--party-a-address", "123 Main St",
                "--party-b", "Beta LLC",
                "--party-b-address", "10 Market Way",
                "--purpose", "evaluating a partnership",
                "--effective-date", "2026-01-15",
                "--out", str(out_md),
                "--out-docx", str(out_docx),
            ],
            cwd=REPO,
        )
        md = out_md.read_text()
        # Party substitutions
        self.assertIn("Acme Inc.", md)
        self.assertIn("Beta LLC", md)
        self.assertIn("123 Main St", md)
        self.assertIn("evaluating a partnership", md)
        self.assertIn("2026-01-15", md)
        # Clause text from quickstart-augmented policy flows through
        self.assertIn("Reject residual-knowledge clauses", md)
        self.assertIn("NDA term", md)
        self.assertIn("survival of", md)
        # Disclaimer present unless --no-disclaimer
        self.assertIn("DRAFT — generated by nda-review-cli", md)
        # Docx structure is valid
        with zipfile.ZipFile(out_docx) as zf:
            names = set(zf.namelist())
            for required in (
                "[Content_Types].xml",
                "_rels/.rels",
                "word/_rels/document.xml.rels",
                "word/document.xml",
                "word/styles.xml",
            ):
                self.assertIn(required, names)
            for name in names:
                # All emitted XML parts must parse
                ET.fromstring(zf.read(name))

    def test_one_way_out_draft_uses_correct_template_and_clause_changes_with_policy(self):
        td = Path(tempfile.mkdtemp(prefix="nda-draft-oneway-"))
        quickstart(td, answers={
            "org_name": "Acme",
            "org_type": "saas",
            "role": "in-house",
            "nda_direction": "disclosing",
            "risk_posture": "balanced",
            "preferred_jurisdictions": "Austria",
            "survival_years": 5,
            "ai_policy": "guardrailed",
            "nda_term_years": 3,
            "return_or_destroy_pref": "either_with_certification",
            "residual_knowledge": "accept",
            "trade_secret_indefinite": True,
            "affiliate_disclosure": "case_by_case",
        })
        out_md = td / "draft.md"
        subprocess.check_call(
            [
                "python3", str(CLI), "draft",
                "--base", str(td),
                "--template", "one-way-out",
                "--disclosing-party", "Acme",
                "--disclosing-party-address", "Main St",
                "--receiving-party", "Vendor Co",
                "--receiving-party-address", "Lake Rd",
                "--purpose", "vendor diligence",
                "--out", str(out_md),
                "--no-disclaimer",
            ],
            cwd=REPO,
        )
        md = out_md.read_text()
        self.assertIn("Vendor Co", md)
        self.assertIn("This Agreement is one-way", md)
        self.assertIn("certification of destruction", md)  # return_or_destroy_pref=either_with_certification
        self.assertIn("Accept narrowly-scoped residual knowledge", md)  # residual_knowledge=accept
        self.assertIn("case-by-case", md)  # affiliate_disclosure=case_by_case
        # Disclaimer omitted with --no-disclaimer
        self.assertNotIn("DRAFT — generated by nda-review-cli", md)

    def test_common_paper_mutual_template_renders_with_attribution(self):
        td = Path(tempfile.mkdtemp(prefix="nda-draft-cp-"))
        quickstart(td)
        out_md = td / "output" / "drafts" / "cp-mutual.md"
        out_docx = td / "output" / "drafts" / "cp-mutual.docx"
        subprocess.check_call(
            [
                "python3", str(CLI), "draft",
                "--base", str(td),
                "--template", "common-paper-mutual",
                "--party-a", "Acme Inc.",
                "--party-a-address", "123 Main St",
                "--party-b", "Beta LLC",
                "--party-b-address", "10 Market Way",
                "--purpose", "evaluating a partnership",
                "--governing-law", "California",
                "--effective-date", "2026-05-10",
                "--out", str(out_md),
                "--out-docx", str(out_docx),
            ],
            cwd=REPO,
        )
        md = out_md.read_text()
        # Cover-page placeholders fill
        self.assertIn("Acme Inc.", md)
        self.assertIn("Beta LLC", md)
        self.assertIn("123 Main St", md)
        self.assertIn("10 Market Way", md)
        self.assertIn("evaluating a partnership", md)
        self.assertIn("2026-05-10", md)
        self.assertIn("Governing Law: California", md)
        # Standard Terms verbatim text from Common Paper Version 1.0 is preserved
        self.assertIn("Common Paper Mutual NDA Standard Terms Version 1.0", md)
        self.assertIn("Use and Protection of Confidential Information", md)
        self.assertIn("Equitable Relief", md)
        # Section 9 has governing_law substituted (was placeholder)
        self.assertIn("the laws of the State of California", md)
        # CC BY 4.0 attribution preserved at the foot (license requirement)
        self.assertIn("free to use under [CC BY 4.0]", md)
        # Developer-facing HTML comment block stripped from rendered output
        self.assertNotIn("SOURCE:  Common Paper Mutual Non-Disclosure Agreement", md)
        self.assertNotIn("<!--", md)
        # Docx structure is valid and also doesn't contain the developer comment
        with zipfile.ZipFile(out_docx) as zf:
            doc = zf.read("word/document.xml").decode()
            self.assertNotIn("SOURCE:", doc)
            self.assertIn("Common Paper Mutual Non-Disclosure Agreement", doc)
            for name in zf.namelist():
                ET.fromstring(zf.read(name))

    def test_missing_placeholders_exit_2(self):
        td = Path(tempfile.mkdtemp(prefix="nda-draft-miss-"))
        quickstart(td)
        result = subprocess.run(
            [
                "python3", str(CLI), "draft",
                "--base", str(td),
                "--template", "mutual",
                "--party-a", "Acme",  # missing party-a-address, party-b, party-b-address
                "--purpose", "x",
                "--out", str(td / "draft.md"),
            ],
            cwd=REPO,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 2)
        payload = json.loads(result.stdout)
        self.assertFalse(payload["ok"])
        self.assertIn("party_a_address", payload["missing_placeholders"])
        self.assertIn("party_b", payload["missing_placeholders"])

    def test_no_policy_exits_2_with_friendly_error(self):
        td = Path(tempfile.mkdtemp(prefix="nda-draft-noconf-"))
        # Intentionally do NOT run quickstart.
        result = subprocess.run(
            [
                "python3", str(CLI), "draft",
                "--base", str(td),
                "--template", "mutual",
                "--party-a", "A", "--party-a-address", "1",
                "--party-b", "B", "--party-b-address", "2",
                "--purpose", "x",
                "--out", str(td / "draft.md"),
            ],
            cwd=REPO,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 2)
        payload = json.loads(result.stdout)
        self.assertFalse(payload["ok"])
        self.assertIn("quickstart", payload["error"])


if __name__ == "__main__":
    unittest.main()
